version: 2.1
orbs:
  node: circleci/node@4.7.0
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Install FFMPEG
          command: sudo apt-get install -y ffmpeg
      - run:
          name: Install testcafe
          command: yarn
      - run:
          name: run tests
          command: testcafe
      - store_test_results:
          path: /tmp/test-results
workflows:
  e2e-test:
    jobs:
      - test